name: simple_api
services:
  postgresql:
    container_name: postgresql
    image: postgres:17-alpine
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/pg_data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      PGDATA: /var/lib/postgresql/data/pg_data

volumes:
  pg_data: