name = "examples"
version = "1.0.0"
description = "A collection of ewe examples"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
ewe = { path = "../" }
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_crypto = ">= 1.5.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
